# Add JSON schema to describe YAML structure

name: Production Deployment Quality
repository: zendranm/scorecards-redocly
timeWindow:
  duration: 1
  type: rolling

rules:
  - id: min-deployments
    type: min_successful
    threshold: 3
    description: At least 3 successful deployments per day

  - id: max-failures
    type: max_failed
    threshold: 1
    description: At most 1 failed deployment per day
